; ***************************************************************************************
; ***************************************************************************************
;
;		Name : 		m7.asm
;		Author :	Paul Robson (paul@robsons.org.uk)
;		Date : 		15th October 2021
;		Purpose :	M7 Main.
;
; ***************************************************************************************
; ***************************************************************************************

CodeStart = 0xC000
CodeEnd = 0xFFFF

	.org CodeStart

; ***************************************************************************************
;
; 									  Code Header
;
; ***************************************************************************************

start: 								
	ld 		hl,(StartAddress) 				; running from here
	jp 		(hl) 							

InformationBlock:
	.word 	start 							; +$00 base address of kernel
	.word 	InterfaceHandler 				; +$02 Interface routine
	.word 	DataArea 						; +$04 Data Area
	
	.include "kernel/data.asm" 				; data area.
	.include "kernel/kernel.asm"			; kernel code.	

; ***************************************************************************************
;
; 							Autogenerated Vocabulary file
;
; ***************************************************************************************

	.include 	"vocabulary/vocabulary.asm"
FreeSpace:

; ***************************************************************************************
;
;										ROM Header
;
; ***************************************************************************************

	.org	$E000
	.db  	"PSR",0 						; 4 bytes filler.
	.db  	0,$9C,0,$B0,0,$6C 				; 12 bytes ROM Identify
	.db 	0,$64,0,$A8,$5F,$70 			; the $5F makes the total $70 so $00 is output to scrambler
	.org 	$E010
	jp 		start 							; BIOS enters here.


	.org 	$E100
testCode:
	.incbin "m7source.bin"

; ***************************************************************************************
;
; 				Load the Dictionary into High memory, it works down.
;
; ***************************************************************************************

	.include "vocabulary/dictionary.inc" 	; get length
	.org 	CodeEnd-DictionarySize+1 		; set start pointer
DictionaryInstalledBase:
	.include "vocabulary/dictionary.asm" 	; pregenerated dictionary.